[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3 --log-format serial"
linker = "xtensa-esp32s3-elf-gcc"

[env]
DEP_LV_CONFIG_PATH = { value = "conf", relative = true }
CC_xtensa_esp32s3_none_elf = "xtensa-esp32s3-elf-gcc"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
